name: color_picker
description: "Simple color picker app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_acrylic: ^1.1.0

  hotkey_manager: ^0.2.3

  window_manager: ^0.5.1
  
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/colorPicker.png"
    icon_size: 256

